"""
protocol.py

Protocol definitions for USB communication.
"""

PROTOCOL_VERSION = "1.0"

COMMANDS = {

    "PING",

    "CAPTURE_IMAGE",

    "GET_CAMERA_INFORMATION",

    "GET_CAMERA_STATUS",

    "GET_STORAGE_INFORMATION",

    "GET_CONFIGURATION",

    "SELF_TEST",

    "SHUTDOWN",

    "DOWNLOAD_IMAGE",

    "DELETE_IMAGE",

    "LIST_IMAGES"

}
#Implementented Protocol Version
PROTOCOL_VERSION = "1.0"

#Commands
PING = "PING"
CAPTURE_IMAGE = "CAPTURE_IMAGE"
GET_CAMERA_INFORMATION = "GET_CAMERA_INFORMATION"
GET_CAMERA_STATUS = "GET_CAMERA_STATUS"
GET_STORAGE_INFORMATION = "GET_STORAGE_INFORMATION"
GET_CONFIGURATION = "GET_CONFIGURATION"
SELF_TEST = "SELF_TEST"
SHUTDOWN = "SHUTDOWN"
DOWNLOAD_IMAGE = "DOWNLOAD_IMAGE"
DELETE_IMAGE = "DELETE_IMAGE"
LIST_IMAGES = "LIST_IMAGES"


#status 
STATUS_OK = "OK"
STATUS_ERROR = "ERROR"
